SOF_HEADER = b"__START"
EOF_FOOTER = b"__END__"
EOR_FOOTER = b"__ROW__"

IMAGE_W = 154
IMAGE_H = 120
BYTES_PER_PIXEL = 2
IMAGE_BYTES = IMAGE_W*IMAGE_H*BYTES_PER_PIXEL

YUV_FORMAT = 0
RGB565_FORMAT = 1

REG_TEST_ON = (0xFF, 0)
REG_TEST_OFF = (0xFF, 1)
REG_HMIRROR_ON = (0xFF, 2)
REG_HMIRROR_OFF = (0xFF, 3)
REG_VFLIP_ON = (0xFF, 4)
REG_VFLIP_OFF = (0xFF, 5)
REG_COLOR_BAR_ON = (0xFF, 6)
REG_COLOR_BAR_OFF = (0xFF, 7)
REG_RGB565 = (0xFF, 8)
REG_YUV = (0xFF, 9)