SOF_HEADER = b"__START"
EOF_FOOTER = b"__END__"
EOR_FOOTER = b"__ROW__"

IMAGE_W = 154
IMAGE_H = 120
BYTES_PER_PIXEL = 2
IMAGE_BYTES = IMAGE_W*IMAGE_H*BYTES_PER_PIXEL

YUV_FORMAT = 0
RGB565_FORMAT = 1

REG_TEST_ON = "0"
REG_TEST_OFF = "1"
REG_HMIRROR_ON = "2"
REG_HMIRROR_OFF = "3"
REG_VFLIP_ON = "4"
REG_VFLIP_OFF = "5"
REG_COLOR_BAR_ON = "6"
REG_COLOR_BAR_OFF = "7"
REG_RGB565 = "a"
REG_YUV = "9"